# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FirebaseTest2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'SnapKit', '~> 5.6.0'

  # Pods for FirebaseTest2

end
